### ISSUE TITLE
Icingaweb2 version 2.8.2

### ISSUE THREAD

**Issue by daku69** [morgajel/icingaweb2-module-boxydash#6]
In the title: Undefined variable: host
#0 /usr/share/icingaweb2/modules/boxydash/application/views/scripts/index/index.phtml(52): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/php/Icinga/Web/View.php(248): include(String)
#2 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run(String)
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(NULL)
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript(String, NULL)
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Dispatcher/Standard.php(303): Zend_Controller_Action->dispatch(String)
#9 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(56): Zend_Controller_Dispatcher_Standard->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#13 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#14 {main}

**Comment by slavkoja** [comment]
I meet the same problem on Debian testing, with its boxydash package (0.0.1) and icingaweb2 (2.8.2), see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=977714

**Comment by slavkoja** [comment]
It was fixed in debian. The problem is/was short PHP tags.

**Comment by daku69** [comment]
Can you add this change in Upstream.
`diff -Naurp icingaweb2-module-boxydash-orig/application/views/scripts/index/index.phtml icingaweb2-module-boxydash/application/views/scripts/index/index.phtml
--- icingaweb2-module-boxydash-orig/application/views/scripts/index/index.phtml
+++ icingaweb2-module-boxydash/application/views/scripts/index/index.phtml
@@ -1,4 +1,4 @@
-<?
+<?php
 use Icinga\Module\Monitoring\Object\Service;
 use Icinga\Module\Monitoring\Object\Host;
 
@@ -15,7 +15,7 @@ use Icinga\Module\Monitoring\Object\Host
 <div class="content">
 
     <h1>Boxy Dashboard</h1>
-    <? if ($this->showlegend){ ?>
+    <?php if ($this->showlegend){ ?>
     <div class="boxy_legend">
         <span class="boxy_sublegend">
             <span class="legendtext">&#10004; = Acknowledged</span>
@@ -36,9 +36,9 @@ use Icinga\Module\Monitoring\Object\Host
             <span class="boxy_legend_box unknown-ack" >unknown</span>
         </span>
     </div>
-    <? } ?>
+    <?php } ?>
 <h2>Host Info</h2>
-<?
+<?php
 foreach ($this->hosts as $host){
     $title = htmlspecialchars($host->{'host_display_name'});
     $size=$this->boxsize;
@@ -50,12 +50,12 @@ foreach ($this->hosts as $host){
         $title.=" (Acknowledged)";
     }?>
     <a href='<?= $this->path_prefix ?>/monitoring/host/show?host=<?=$host->{'host_name'}?>' class='boxy_box state <?=$returncode?>' style='width:<?=$size?>px; height:<?=$size?>px; font-size:<?=$size?>px;' title="<?=$title?>"><?=$content?></a>
-<? } ?>
+<?php } ?>
 
 <br clear="all"/>
 <h2>Service Info</h2>
 
-<? foreach ($this->services as $service){
+<?php foreach ($this->services as $service){
     $service->{'service_hard_state'} = ($service->{'service_hard_state'}) ? "hard" : "soft";
     $title = $service->{'host_display_name'}.": ".$service->{'service_description'};
     #."(".$service->{'current_check_attempt'} .",".$service->{'max_check_attempts'} .")(". $service->{'service_hard_state'}.")+acked:".$service->{'service_acknowledged'} ;
@@ -78,7 +78,7 @@ foreach ($this->hosts as $host){
     $title=htmlspecialchars($title."\n ".$service->{'service_output'});?>
     <a href='<?= $this->path_prefix ?>/monitoring/service/show?host=<?=$service->{'host_name'}?>&service=<?=$service->{'service_description'}?>' class='boxy_box state <?=$returncode?>' style='width:<?=$size?>px; height:<?=$size?>px; font-size:<?=$size?>px;' title="<?=$title?>"><?=$content?></a>
 
-<? } ?>
+<?php } ?>
 <br clear=all>
 <pre style="font-size:20px"><?=$this->debug?></pre>
 </div>`
